Hackathon Submission: Search Ideas List
appwrite-community/htf24-hackathon-submissions pull request #12
Opened 2024-10-06 14:53 UTC by leonyangela

# Hackathon Submission: Search Ideas List

## Name of Team Lead
- Leoni Angela

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_
- @leonyangela 

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [x] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

2024-10-07 15:26 UTC, adityaoberai commented
@leonyangela please make a copy of the `template_submission` file instead of editing it, as specified in the repo readme. Also, please upload your project codebase into your own repository and link that in your submission, instead of adding the project codebase here

2024-10-14 12:43 UTC, leonyangela commented
Hi @adityaoberai, I have updated the submission, thank you.

2024-10-18 22:02 UTC, adityaoberai requested changes

2024-10-18 22:02 UTC, adityaoberai commented on .gitignore
Please remove this file from the PR

2024-10-18 22:02 UTC, adityaoberai commented on submissions/template_submission.md
Please remove this edit from the PR

2024-10-20 05:40 UTC, leonyangela commented on submissions/template_submission.md
fixed, please check it, thanks

2024-10-22 12:56 UTC, adityaoberai approved these changes

2024-10-22 12:57 UTC, merged