Project: News-Web
appwrite-community/htf24-hackathon-submissions pull request #3
Opened 2024-10-01 14:27 UTC by sammyifelse

# Hackathon Submission: <PROJECT_NAME>

## Name of Team Lead
_Enter your full name_

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [ ] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

2024-10-01 14:44 UTC, adityaoberai commented
@sammyifelse thanks a lot for submitting your PR! You can continue making updates to your PR and we'll review and merge these closer to the end of the month

2024-10-01 14:46 UTC, adityaoberai requested changes
@sammyifelse please make a copy of the `template_submission` file instead of editing it

2024-10-01 15:10 UTC, sammyifelse commented
so i have to make a new file named template_submission?

2024-10-01 15:17 UTC, adityaoberai commented
> ok i have made a new template_submission1.md file where i have copied the content of my project istead of editing the main template_submission.md file

You can rename the file to your project's name instead of `template_submission1.md`

2024-10-01 15:22 UTC, sammyifelse commented
Done

2024-10-01 19:15 UTC, CodeWithKamal commented
sorry guys, accidental clicked caused closed PR. how to undo this? I tried deleting that branch. @adityaoberai

2024-10-02 05:42 UTC, sammyifelse commented
PR is not merged till now??

2024-10-15 18:30 UTC, adityaoberai requested changes

2024-10-15 18:30 UTC, adityaoberai commented on .vscode/settings.json
Please remove this file from the PR @sammyifelse

2024-10-18 13:54 UTC, adityaoberai approved these changes

2024-10-18 22:20 UTC, adityaoberai commented
@sammyifelse thank you for your submission. Unfortunately, it is ineligible for this hackathon because, as visible in the project's  [commit history](https://github.com/sammyifelse/News-Web/commits/master/), the project has been made before the hackathon began.

![image](https://github.com/user-attachments/assets/1f59a2b3-b758-497d-b4ec-3a69c75a0f24)

As stated in the rules, the project must be built in its entirety within the month of October only. Older projects are not allowed. You can build and submit another project if you like, however, we will not be accepting this one.

2024-10-18 22:20 UTC, closed without merging