Todo list app backend
appwrite-community/htf24-hackathon-submissions pull request #46
Opened 2024-10-21 17:43 UTC by sahilrawat001

# Hackathon Submission: <PROJECT_NAME>

## Name of Team Lead
_Enter your full name_

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [ ] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

2024-10-23 18:03 UTC, sahilrawat001 commented
done with the changes

2024-10-26 10:39 UTC, adityaoberai commented on submissions/sahil_todo.md
> +[_Share a public repo link of your project_](https://github.com/sahilrawat001/app-write)
Please add the repo link to a separate line

2024-10-26 10:40 UTC, adityaoberai requested changes

2024-10-26 10:40 UTC, adityaoberai commented on submissions/sahil_todo.md
> +_Share a 2-3 minute demo video or photos or a deployed link of your project_
It is mandatory to submit a demo video @sahilrawat001

2024-11-01 13:50 UTC, adityaoberai commented
@sahilrawat001 I am accepting this PR because it has a valid project, however, not having a demo will be penalized in judging

2024-11-01 13:51 UTC, adityaoberai approved these changes

2024-11-01 13:51 UTC, merged