Create astroappwritestarter.md
appwrite-community/htf24-hackathon-submissions pull request #59
Opened 2024-10-27 08:43 UTC by petipois

submission for the hackathon

# Hackathon Submission: <PROJECT_NAME>

## Name of Team Lead
_Enter your full name_

## GitHub handles of Team Members  
_Enter the GitHub handles of all your team members (including yourself) as separate bullet points_

### Are all of your team members registered on our [Hackathon Signup page](https://apwr.dev/htf24-hackathon)?
_This is a mandatory step for all participants to be considered eligible for judging_

- [ ] Yes
- [ ] No

---

## Rules and Code of Conduct  
By submitting this PR, you agree to follow our Rules and Code of Conduct.

- [x] Yes

---

## Anything Else?  
_Any other feedback, queries or information you would like to share with us?_

2024-10-28 12:03 UTC, adityaoberai requested changes

2024-10-28 12:03 UTC, adityaoberai commented on submissions/astroappwritestarter.md
> +-->
Please add a demo as this is mandatory for the submission @petipois

2024-10-29 00:26 UTC, petipois commented
I updated the video link

2024-10-29 00:27 UTC, petipois reviewed
Added video link

2024-10-29 07:09 UTC, adityaoberai approved these changes

2024-10-29 07:09 UTC, merged